### ISSUE TITLE
scripts 01 to 04 - annotations + plot GAM outputs

### ISSUE THREAD

**Issue by vjjan91** [vjjan91/nilgiris-resurvey-project#7]
Hi @pratikunterwegs,

Two small tasks:

a) Would you be able to annotate scripts 01-04 in detail so that I can read the code and understand it better?
b) https://github.com/vjjan91/nilgiris-resurvey-project/blob/7f2eee8adbf18309650d2361ab789fe10587d0e4/05_climate-change-analysis.Rmd#L362 - would you be able to visualize the results from L362? (I was playing around with library(mgcviz), but this could be a potential visualization for the supplementary data. 

-all associated data and objects are not up on git for you to reproduce the same.

**Comment by vjjan91** [comment]
If scripts could be annotated similar to this repo[ https://github.com/vjjan91/diurnal-Acoustics/blob/main/02_vocal-activity.Rmd] or our eBird repo, that would be great. Thanks, Pratik!

**Comment by pratikunterwegs** [comment]
Sure, I can get to this by this Wednesday.

> -all associated data and objects are not up on git for you to reproduce the same.

About this, so the data are _not_ on GH, or they are?

**Comment by vjjan91** [comment]
Thanks! All the data is now on GH, _barring the CHELSA rasters and the historical climate data (which I thought we can push to Zenodo before pub_. For script05 - I think you should have what you need pushed to Git

**Comment by pratikunterwegs** [comment]
> CHELSA rasters and the historical climate data

I think I have this locally - yes, we should definitely get a Zenodo archive going.

Could you also re-open the issue? That way when I make a PR to your `main` from my fork I can tag this issue for reference. Merging that PR will automatically close the issue if I use the right keywords.

**Comment by vjjan91** [comment]
To provide more context to my above request, I was thinking of a figure for this accompanying sentence/similar in the main text: "Analysis of climate data revealed a significant increase in mean monthly temperatures across the study area over time (XX- YY deg C; some statistical test..)"

**Comment by vjjan91** [comment]
Is there anyway in which we can add an additional figure to include minimum temperatures (monthly) and their increase over time? I basically want to make a case for reduction in number of frost days in the dry season (so plotting this data just for winter/dry season) to show that min temp has also gone up?

**Comment by pratikunterwegs** [comment]
Sorry, forgot to reply here - yes, we could add minimum monthly temperatures. My only caveat would be that when we looked into this previously, we consistently got values well above freezing. I guess the main reason is that these are extreme events whose signature/driver (min temp <= 0C) is averaged out in monthly data.

**Comment by vjjan91** [comment]
Hmm...I see your point. I think including it would still be useful to perhaps show that the trend is that there is an increase in the temperatures over time? But yeah, I do understand that the values are largely above freezing...

**Comment by pratikunterwegs** [comment]
Can we open a new issue for the minimum temperature plot? Just helps me keep track of what needs doing. I won't be able to get around to it before I go on holiday this Friday - I want to get the annotations done first - but should get around to it next weekend.
